# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8d5751bae72be8328d5571b42eb5ea128c41205e7001499512a8c2100d5055de8c4c96c442fd4931934d99951e010aeeb983c49dd44c2b7b31987b8f2f35e7dd

test:
  secret_key_base: e91bd5294a15222128e95ce356176cc842e27b693b7a01da43d56a0bf06e3ab8522e7c4814f67e2e58451b11b66e809ac46c0ad33af72c0dd0512a2e106ce2a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
